name: Windows Build
on:
  push:
jobs:
  build:
    name: Windows Build
    permissions: write-all
    runs-on: windows-latest
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v4.1.7

      - name: Setting up Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.5

      - name: Restore existing build cache for faster compilation
        uses: actions/cache@v4
        with:
          key: cache-build-windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          restore-keys: |
            cache-build-windows

      - name: Installing haxelibs and fixing versions
        run: |
          haxelib install flixel-addons
          haxelib install flixel-demos
          haxelib install flixel-templates
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel
          haxelib install flxanimate
          haxelib install hscript
          haxelib install lime-samples
          haxelib install lime
          haxelib install openfl
          haxelib install newgrounds
          haxelib install actuate
          haxelib install format

          haxelib set flixel-addons 3.0.2
          haxelib set flixel-demos 2.9.0
          haxelib set flixel-templates 2.6.6
          haxelib set flixel-tools 1.5.1
          haxelib set flixel-ui 2.5.0
          haxelib set flixel 5.2.2
          haxelib set flxanimate 3.0.4
          haxelib set hscript 2.5.0
          haxelib set lime-samples 7.0.0
          haxelib set lime 8.0.1
          haxelib set openfl 9.2.1
          # Add version sets for actuate and format if necessary
        shell: cmd

      - name: Installing hscript-improved from GitHub
        run: |
          haxelib git hscript-improved https://github.com/YOUR_REPO/hscript-improved.git
        shell: cmd

      - name: Installing/Updating libraries
        run: |
          haxe -cp setup -D analyzer-optimize -main Main --interp
        shell: cmd

      - name: Building the game
        run: |
          haxelib run lime build windows

      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4.3.4
        with:
          name: Win64_SlushiEngine
          path: export/release/windows/bin

      - name: Clearing already existing cache
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-windows") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }

      - name: Uploading new cache
        uses: actions/cache@v4
        with:
          key: cache-build-windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          restore-keys: |
            cache-build-windows
